# service
apiVersion: v1
kind: Service
metadata:
  name: nginx-index-cm
  labels:
    app: nginx-index-cm
spec:
  selector:
    app: nginx-index-cm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: ClusterIP
